jdkVersion = "17"

# Ignore warnings not relevant to this specific project:
#
# 1) FindSecBugs identifies our use of ThreadLocalRandom as predictable.
# We make extensive use of this class since local search require randomness.
# Our use of randomness is NOT at all security related,
# and rather, we simply need a fast pseudorandom number generator since
# we need to generate large numbers of random numbers. So ignore
# predictable random warnings. 
#

ignoreRules = ["PREDICTABLE_RANDOM"]
